
class SerializedNodeCollection: public RefCounted {
GDCLASS(SerializedNodeCollection, RefCounted);
public:
Array node_configs;
Array property_lists;
Array prev_property_lists;
int num_nodes;
int uid;
int scene_id;
int owner_id;
int team;
int frame_created;
int frame_deleted;
int visibility;
Node spawn(Node scene);
bool was_deleted();
String _to_string();
void update_interpolation(Array new_property_lists);
RefCounted duplicate();
static RefCounted create_fresh(int uid, int scene_id, int owner_id, int team, int frame_created, Array node_configs);
void _init(Array property_lists, int uid, int scene_id, int owner_id, int team, int frame_created, Array node_configs, bool duplicate);
void encode_spawn(StreamPeerBuffer buffer, int vis_type);
void decode_spawn(StreamPeerBuffer buffer, int vis_type);
void encode_delta(RefCounted prev, StreamPeerBuffer buffer, int vis_type);
void decode_delta(StreamPeerBuffer buffer, int vis_type);
Array get_node_configs();
Array set_node_configs(Array node_configs);
Array get_property_lists();
Array set_property_lists(Array property_lists);
Array get_prev_property_lists();
Array set_prev_property_lists(Array prev_property_lists);
int get_num_nodes();
int set_num_nodes(int num_nodes);
int get_uid();
int set_uid(int uid);
int get_scene_id();
int set_scene_id(int scene_id);
int get_owner_id();
int set_owner_id(int owner_id);
int get_team();
int set_team(int team);
int get_frame_created();
int set_frame_created(int frame_created);
int get_frame_deleted();
int set_frame_deleted(int frame_deleted);
int get_visibility();
int set_visibility(int visibility);
};
