#include byte_utils.h
#include stream_peer_bit_buffer.h

class StreamPeerBitBuffer: public StreamPeerBuffer {
GDCLASS(StreamPeerBitBuffer, StreamPeerBuffer);
public:
int bool_position;
int num_allocated_bools;
int bool_bytes;
String _to_string();
void reset();
void _init(int with_size, int allocated_bools);
PackedByteArray export(bool until_position);
void import(PackedByteArray bytes);
PackedByteArray get_bools(bool until_position);
static StreamPeerBuffer decode(PackedByteArray bytes);
PackedByteArray get_non_bools(bool until_position);
Array get_bools_as_array();
void ensure_bools_allocated();
void reallocate_bools(int amount);
void put_bool(bool value);
bool put_eval(bool evaluation);
bool get_bool();
void seek_var_pos(int position);
int get_var_pos();
void jump(int amount);
void put_v2(Vector2 v2);
Vector2 get_v2();
void put_v3(Vector3 v3);
Vector3 get_v3();
void put_v4(Vector4 v4);
Vector4 get_v4();
void put_v2i(Vector2i v2);
Vector2i get_v2i();
void put_v3i(Vector3i v3);
Vector3i get_v3i();
void put_v4i(Vector4i v4);
Vector4i get_v4i();
void put_r2(Rect2 r2);
Rect2 get_r2();
void put_r2i(Rect2i r2i);
Rect2i get_r2i();
void put_quat(Quaternion quat);
Quaternion get_quat();
void put_color(Color color);
Color get_color();
void put_udynamic(int num);
int get_udynamic();
void put_dynamic(int num);
int get_dynamic();
void put_n8(float num, float unit);
float get_n8(float unit);
void put_n16(float num, float unit);
float get_n16(float unit);
void put_n32(float num, float unit);
float get_n32(float unit);
void put_n64(float num, float unit);
float get_n64(float unit);
void put_r8(float num, float unit);
float get_r8(float unit);
void put_r16(float num, float unit);
float get_r16(float unit);
void put_r32(float num, float unit);
float get_r32(float unit);
void put_r64(float num, float unit);
float get_r64(float unit);
void put_rotation(Vector3 rot);
Vector3 get_rotation();
void put_rotation_half(Vector3 rot);
Vector3 get_rotation_half();
void put_nv2(Vector2 v2, float unit);
Vector2 get_nv2(float unit);
void put_rv2_half(Vector2 v2, float unit);
Vector2 get_rv2_half(float unit);
void put_nv2_half(Vector2 v2, float unit);
Vector2 get_nv2_half(float unit);
void put_probabalistic_enum(int value);
int get_probabalistic_enum(int enum_max);
int get_bool_position();
int set_bool_position(int bool_position);
int get_num_allocated_bools();
int set_num_allocated_bools(int num_allocated_bools);
int get_bool_bytes();
int set_bool_bytes(int bool_bytes);
};
