name: 🔗 GHA
on: [push, pull_request, merge_group]

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  # First stage: Only static checks, fast and prevent expensive builds from running.

  static-checks:
    if: ${{ !vars.DISABLE_GODOT_CI || github.run_attempt > 1 }}
    name: 📊 Static checks
    uses: ./.github/workflows/static_checks.yml

  # Second stage: Run all the builds and some of the tests.

  android-build:
    name: 🤖 Android
    needs: static-checks
    uses: ./.github/workflows/android_builds.yml

  ios-build:
    name: 🍏 iOS
    needs: static-checks
    uses: ./.github/workflows/ios_builds.yml

  linux-build:
    name: 🐧 Linux
    needs: static-checks
    uses: ./.github/workflows/linux_builds.yml

  macos-build:
    name: 🍎 macOS
    needs: static-checks
    uses: ./.github/workflows/macos_builds.yml

  windows-build:
    name: 🏁 Windows
    needs: static-checks
    uses: ./.github/workflows/windows_builds.yml

  web-build:
    name: 🌐 Web
    needs: static-checks
    uses: ./.github/workflows/web_builds.yml
  release:
    name: Create Download Links
    needs: [static-checks, linux-build]
    uses: ncipollo/release-action/blob/440c8c1cb0ed28b9f43e4d1d670870f059653174/.github/workflows/release.yml@v1.16.0
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      generateReleaseNotes: true
      tag: ${{ github.ref_name }}
      artifacts: ${{ steps.export.outputs.archive_directory }}/* # Added "/*" at the end is glob pattern match for this action
